# Generated by Django 4.0.4 on 2022-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(max_length=50)),
                ('receptor', models.CharField(max_length=50)),
                ('contenido', models.TextField(default='Escribir mensaje aqui')),
                ('fecha_envio', models.TextField(default='2022-06-01 14:05:40.575265')),
            ],
        ),
    ]
