# Generated by Django 4.0.4 on 2022-05-29 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
