# Generated by Django 4.0.4 on 2022-06-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_blog_fecha_creacion_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha_creacion',
            field=models.TextField(default='2022-06-01 14:05:40.560073'),
        ),
    ]
