# Generated by Django 4.0.4 on 2022-06-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_blog_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creador',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha_creacion',
            field=models.TextField(default='2022-06-06 16:32:56.221639'),
        ),
    ]
