# Generated by Django 4.0.4 on 2022-06-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_blog_imagen_alter_blog_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha_creacion',
            field=models.TextField(default='2022-06-06 16:07:39.626388'),
        ),
    ]
