# Generated by Django 4.0.4 on 2022-06-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_blog_creador_blog_imagen_alter_blog_fecha_creacion'),
        ('app1', '0011_alter_blog_fecha_creacion'),
    ]

    operations = [
    ]
